### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by vweevers** [Level/level-js#103]

**Comment by ralphtheninja** [comment]
TODO

- [ ] `Leveljs.binaryKeys`
- [ ] `Leveljs.arrayKeys`

**Comment by vweevers** [comment]
Should those be public though? I didn't think about that part

**Comment by ralphtheninja** [comment]
Actually, unassigning myself. Better if @vweevers does this.

**Comment by ralphtheninja** [comment]
> Should those be public though? I didn't think about that part

They could be just `var binaryKeys = ..` etc instead.

**Comment by ralphtheninja** [comment]
I think in general it's probably easiest to take the same structure from `leveldown` and take one method at a time instead of copying over docs from `leveldown` and tweaking it.

**Comment by vweevers** [comment]
I'm not sure we even need API docs beyond the constructor (where it differs from `abstract-leveldown`).

**Comment by ralphtheninja** [comment]
> I'm not sure we even need API docs beyond the constructor (where it differs from abstract-leveldown).

I should be able to fix _that_ at least :wink:
