### ISSUE TITLE
Test all key types

### ISSUE THREAD

**Issue by vweevers** [Level/level-js#128]
https://github.com/Level/level-js/blob/c471684f704586cdb7201ec859f774fa281255ae/index.js#L114-L122

**Comment by vweevers** [comment]
Hmm, keys and values behave differently atm. Invalid keys (according to the spec, like `NaN`) will be stringified, but invalid values (like `Function`) won't and cause the browser to throw an error.

I think invalid keys should also throw, to avoid surprises. We'd still stringify *valid* keys, to provide reasonable fallbacks. E.g. if the browser doesn't support binary keys, we convert them to strings.

 @ralphtheninja WDYT?

**Comment by vweevers** [comment]
Essentially I mean to remove the `String(key)` at the end of:

https://github.com/Level/level-js/blob/b73567846177832f79210415f85295c9a7af0068/index.js#L124-L134

Which also means we can support ArrayBuffer and TypedArray without type checking.

**Comment by ralphtheninja** [comment]
> Hmm, keys and values behave differently atm. Invalid keys (according to the spec, like NaN) will be stringified, but invalid values (like Function) won't and cause the browser to throw an error.
> 
> I think invalid keys should also throw, to avoid surprises. We'd still stringify valid keys, to provide reasonable fallbacks. E.g. if the browser doesn't support binary keys, we convert them to strings.
> 
> @ralphtheninja WDYT?

I agree. It makes it more clear what is valid and also consistent behavior.

**Comment by vweevers** [comment]
Sadly it breaks the abstract test suite, which tests boolean keys (among other things).

**Comment by vweevers** [comment]
And it also tests NaN :(

**Comment by ralphtheninja** [comment]
Lets leave it hanging for a while and let the thought mature. We can also counter it with good docs.

**Comment by vweevers** [comment]
It can be fixed ad-hoc with a `if (typeof key === 'boolean' || isNaN(key)) return String(key`.

**Comment by vweevers** [comment]
Damn! Just found out that Chrome returns binary keys as strings. The Iterator entries look like `{ key: '0,127', value: 'foo' }`. Though `get()` etc does work.

I entirely missed this. Apparently IndexedDB internally converts keys to a [key construct](https://w3c.github.io/IndexedDB/#key-construct) with an "associated `type` which is one of number, date, string, binary, or array". And with an "associated `value`, which will be either an unrestricted `double` if `type` is number or date, a `DOMString` if `type` is string, a list of `octets` if `type` is binary, or a list of other keys if `type` is array."

So for ArrayBuffer or Typed Array, [the process for converting a key](https://w3c.github.io/IndexedDB/#convert-value-to-key) is:

> If `input` is a *buffer source type*
> - Let `octets` be the result of running the steps to get a copy of the bytes held by the buffer source `input`. Rethrow any exceptions.
> - Return a new key with type `binary` and value `octets`.

This means type information is lost, and the key cannot be converted back to its original type when you access `cursor.key`. I guess Chrome opted to convert the `binary` type to string, hence `'0,127'`.

Where does that leave us? We can either accept that binary keys are broken in Iterators, or serialize Buffers to array keys instead (which do not loose type information, but might have a performance cost).

**Comment by vweevers** [comment]
Nope, hold on, I made a mistake.

**Comment by vweevers** [comment]
The stringification was a side-effect of:

```
> isNaN(Uint8Array.from([0,127]))
true
```
