### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by vweevers** [Level/level-js#140]
~~Don't forget to `--tag next`~~

**Comment by vweevers** [comment]
Remember to remove `npm install level-js@next` and the npm badge from the readme.

**Comment by vweevers** [comment]
Hmm next time I should remember to create the GitHub release before npm publish, so that the changelog shows up in greenkeeper PRs.

**Comment by ralphtheninja** [comment]
Oh I didn't think of that. I've always been doing the github releases afterwards.
