### ISSUE TITLE
Implement `iterator._seek()`

### ISSUE THREAD

**Issue by vweevers** [Level/level-js#178]
See [abstract-leveldown documenation](https://github.com/Level/abstract-leveldown#iteratorseektarget).

**Comment by Bexanderthebex** [comment]
Is this issue open for open source contributors?

**Comment by vweevers** [comment]
Everything is open for contributions! Want to send a PR?

**Comment by Bexanderthebex** [comment]
I want to try! How is this feature different than _get()?

**Comment by vweevers** [comment]
I updated the issue description with a link to documentation.

**Comment by vweevers** [comment]
Done in [`browser-level`](https://github.com/Level/browser-level).
