### ISSUE TITLE
Node.js compatibility?

### ISSUE THREAD

**Issue by rix0rrr** [Level/level-js#196]
So this may be an odd question, and maybe what I want simply cannot be achieved, but here goes anyway:

* I need a fake NPM registry to test some packages we're about to publish locally, before actually publishing them. [Verdaccio](https://github.com/verdaccio/verdaccio), the only game in town, has chosen to use LevelDB to implement its storage.
* The [level](https://github.com/Level/level) package will automatically pick the leveldown implementation in a Node.js environment.
* Leveldown has a compiled component, which requires node-gyp, which requires Python and a compiler.

Result: I cannot run this test on a simple Windows instance, which does not come with Python, nor a compiler. Both of these are a pain and expensive to install on a CI/CD run (given a plain Windows container image), and it's just as much of a pain to now maintain a publishing pipeline for a Windows image with those 2 tools baked in, just to be able to install Verdaccio to run my NPM tests.

Given this is integ tests and I don't really care about performance, I'd like to be able to switch out the `leveldown` implementation for the `level-js` implementation (a compatible but slower JS implementation of leveldown, right?).

Is this something I can do, or something you would consider supporting?

**Comment by vweevers** [comment]
On the latest version of leveldown, you don't necessarily need node-gyp, python, etc, because it ships prebuilt binaries (for 32 and 64 bit windows) inside the npm package.

> I'd like to be able to switch out the leveldown implementation for the level-js implementation

`level-js` only works in browsers (because it's backed by IndexedDB) but there are plenty of alternatives! See https://github.com/Level/awesome#bundles and https://github.com/Level/awesome#stores

**Comment by rix0rrr** [comment]
Thanks for the response!
