### ISSUE TITLE
'json' encoding stringifies data before being inserted into db

### ISSUE THREAD

**Issue by ianwremmel** [Level/level-js#33]
Since JSON is the native encoding to IndexedDB, it shouldn't be necessary to stringify data before storing it. Is it AbstractLevelDOWN that does the conversion? Does it make sense to replace 'json' encoding with `raw:true` when the database is opened?

I'm using the following to make sure I can cleanly work with JSON in both node and browser environments, but it feels like a hack:

package.json:

``` json
  ...
  "browser": {
    "leveldown": "level-js",
  }
  ...
```

index.js:

``` javascript
var levelup = require('levelup');
var leveldown = require('leveldown');
var leveljs = require('level-js');

var options = {
  db: leveldown
};
if (leveljs !== leveldown) {
  options.valueEncoding = 'json';
}
var db = levelup(name, options);
```

**Comment by Ivshti** [comment]
@mcollina good point.

I also have a performance concern about this, but it will be good to see if it actually hurts something. It's possible that it doesn't

**Comment by ianwremmel** [comment]
Hi @Ivshti, we ended up going a different direction. Our primary motivation for using indexeddb was performance rather than offline access. Instead of focusing on building a database engine (because a year ago, that's really what you had to do to practically use indexeddb, even with helper libraries), we instead worked on improving API response times and adjusting UI feedback to improve the initial-load experience.

**Comment by juliangruber** [comment]
if you want level.js to get the raw values, +1 on this pull request: https://github.com/Level/abstract-leveldown/pull/85

**Comment by juliangruber** [comment]
abstract-leveldown@2.5.0 is out! so if you want to bypass encoding completely, simply do this:

```js
db._serializeKey =
db._serializeValue = function (data) { return data }
```

**Comment by dominictarr** [comment]
by the way, since we added custom codecs you could do `valueEncoding: {encode: id, decode: id}` where id is the id function: `function id (e) { return e }`

**Comment by juliangruber** [comment]
The problem was that abstract-leveldown would still (!) convert everything to a string of buffer. That can be bypassed now. So yeah you need to set those options on levelup and leveldown for now.

**Comment by dominictarr** [comment]
oh I see. well, we have `encodeing.buffer: boolean` right, maybe we need `encodeing.string: boolean` and then you can have naked encoding `{encode: id, decode: id, buffer: false, string: false}` ?
