### ISSUE TITLE
Avoid instanceof (for cross-realm support)

### ISSUE THREAD

**Issue by vweevers** [Level/level-js#82]
Rewrite `value instanceof ArrayBuffer` etc.

**Comment by vweevers** [comment]
Only one left actually:

https://github.com/Level/level-js/blob/3a8b861b550ef18fd0b7055e5eb916a0a1f8c33a/index.js#L128

The other one doesn't matter because it's only used on values coming out the IndexedDB:

https://github.com/Level/level-js/blob/3a8b861b550ef18fd0b7055e5eb916a0a1f8c33a/util/mixed-to-buffer.js#L6

**Comment by ralphtheninja** [comment]
What do you mean by cross-realm support and why is instanceof problematic?

**Comment by vweevers** [comment]
See https://jakearchibald.com/2017/arrays-symbols-realms/#multiple-realms

**Comment by vweevers** [comment]
Also https://github.com/jasnell/proposal-istypes

**Comment by vweevers** [comment]
And https://github.com/ljharb?utf8=%E2%9C%93&tab=repositories&q=is-&type=&language=

**Comment by ralphtheninja** [comment]
> So, yeah, feeling pretty hipster right now.

:laughing:

**Comment by vweevers** [comment]
It depends on the likelyhood that the value was created in a different realm. For keys and values coming straight out of `IndexedDB` it doesn't matter - as we know they come from the current realm (where `IndexedDB` and the structured clone algorithm lives).

It pretty much only matters for user input. When a user does `db.get(date)`, that date key might have come from a different realm.

**Comment by vweevers** [comment]
(Likelyhood? Likelihood? Damn you, English)
