### ISSUE TITLE
Prefer backpressure over snapshot guarantees

### ISSUE THREAD

**Issue by vweevers** [Level/level-js#86]
Continuing from https://github.com/Level/level.js/pull/68.

TBD if this should go in v3.

**Comment by vweevers** [comment]
I'm not sure whether to include this in v3 or exactly how to implement it. It can also be added in a minor later, but the thing that bothers me is that the readme states "Store large amounts of data in modern browsers". You can write large amounts of data, sure, but without backpressure, you're gonna run into trouble when reading.

**Comment by vweevers** [comment]
@ralphtheninja thoughts?

**Comment by ralphtheninja** [comment]
I'd skip it for v3 so we can get `level-browserify` out and later `level`. Then we can work on the minor as you mentioned.

**Comment by vweevers** [comment]
Relevant: https://github.com/Level/community/issues/63#issuecomment-455697075 and https://github.com/Level/community/issues/63#issuecomment-455759151. IMO offering proper backpressure is a higher priority now.

**Comment by vweevers** [comment]
I now prefer that we forgo snapshotting guarantees, in favor of backpressure and avoiding a blocking transaction.

**Comment by vweevers** [comment]
Plan:

- [ ] Implement `iterator.all()` with snapshot guarantees. This offers a nice alternative.
  - See https://github.com/Level/abstract-leveldown/issues/380
- [ ] Drop snapshot guarantee from (regular use of) iterators

**Comment by vweevers** [comment]
Done in [`browser-level`](https://github.com/Level/browser-level).
