### ISSUE TITLE
npm based  install on windows failing

### ISSUE THREAD

**Issue by ghost** [Level/level-js#9]
C:_data\leveljs>npm install level-js
npm http GET https://registry.npmjs.org/level-js
npm http 304 https://registry.npmjs.org/level-js
npm http GET https://registry.npmjs.org/abstract-leveldown
npm http GET https://registry.npmjs.org/isbuffer/0.0.0
npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "level-js"
npm ERR! cwd C:_data\leveljs
npm ERR! node -v v0.10.7
npm ERR! npm -v 1.2.21
npm ERR! code ENOGIT
npm http 304 https://registry.npmjs.org/isbuffer/0.0.0
npm http 304 https://registry.npmjs.org/abstract-leveldown
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:_data\leveljs\npm-debug.log
npm ERR! not ok code 0

**Comment by nokelong** [comment]
To add git  into system PATH:

Right-Click on My Computer
Click on Advanced System Settings
Click on Environment Variables
Then, under System Variables, look for the path variable and click edit
Add the path to git’s bin and cmd at the end of the string like this:
git  located in my 'D:\Program Files (x86)\Git\bin' 
;D:\Program Files (x86)\Git\bin

**Comment by elho2007** [comment]
> To add git into system PATH:
> 
> Right-Click on My Computer
> Click on Advanced System Settings
> Click on Environment Variables
> Then, under System Variables, look for the path variable and click edit
> Add the path to git’s bin and cmd at the end of the string like this:
> git located in my 'D:\Program Files (x86)\Git\bin'
> ;D:\Program Files (x86)\Git\bin

So simple! Thank you
