### ISSUE TITLE
Move levelup integration tests to level-browserify

### ISSUE THREAD

**Issue by vweevers** [Level/level-js#96]
See https://github.com/Level/level.js/blob/master/test/test-levelup.js. It also tests `encoding-down`.

@ralphtheninja WDYT? On the one hand: can't hurt, and we don't have browser tests in `encoding-down` yet. On the other hand, it doesn't belong here, and we do already have browser tests in `levelup`. I have no strong opinion.

**Comment by ralphtheninja** [comment]
We could move them to `level-browserify` instead?

**Comment by vweevers** [comment]
Good idea.
